@startuml

class FloorRecyclerViewAdapter{
onCreateViewHolder()
onBindViewHolder()
}

class FloorViewHolder extends ViewHolder {
showData(BaseTemplateEntity entity, Object payload)
}

FloorRecyclerViewAdapter +-- FloorViewHolder
note "FloorRecyclerViewAdapter的内部类" as annotation2
FloorViewHolder ..annotation2

class SupportRecommendAdapter{
}


class OrderDetailAdapter{
ArrayList: String[] mDataList
}
note "商祥适配器" as annotation1
OrderDetailAdapter ..annotation1


SupportRecommendAdapter <|--  OrderDetailAdapter
FloorRecyclerViewAdapter <|--  SupportRecommendAdapter


class FloorManagerProxy{
-Map: Map<String, FloorManager> managerMap
+getInstances()
}



@enduml

