# 文档：https://flutter.dev/docs/development/accessibility-and-localization/internationalization

#/Users/huchangjie/Documents/huchangjie_github/HucjTest/flutter_module/lib/l10n
arb-dir: flutter_module/lib/l10n
template-arb-file: intl_en.arb
output-localization-file: deer_localizations.dart
output-class: DeerLocalizations
use-deferred-loading: false
