@startuml
'https://plantuml.com/sequence-diagram
'云修老登陆'

autonumber

LoginActivity -> LoginActivity: actionLogin()
note left:点击登陆

LoginActivity -> LoginPresenter: login()
note right:有效性校验

LoginPresenter -> Net:login()(/legend/app/login)
Net --> LoginPresenter
LoginPresenter --> LoginActivity:loginSuccess()
LoginActivity -> LoginPresenter:getUserData()
LoginPresenter -> Net:getShopTag() (/legend/app/shop/tag)
Net --> LoginPresenter
LoginPresenter -> LoginPresenter:getUserInfo()
LoginPresenter -> Net:getUserInfo() (/legend/app/user/info)
Net --> LoginPresenter
LoginPresenter -> LoginActivity:getUserDataSuccess()


@enduml