@startuml
'https://plantuml.com/activity-diagram-beta

start
:RegisterActivity.onCreate();

switch(currentFragment)
    case (FRAGMENT_FILL_IN_ACCOUNT)
        :FillInAccountInformationFragment;
        note right:填写账号信息
        /'区分企业公司、政府军队'/
    case (FRAGMENT_SUPPLEMENTARY)
        :SupplementaryEnterpriseInformationFragment;
        note left:补充填写企业信息










:new page;
if (Page.onSecurityCheck) then (true)
  :Page.onInit();
  if (isForward?) then (no)
    :Process controls;
    if (continue processing?) then (no)
      stop
    endif

    if (isPost?) then (yes)
      :Page.onPost();
    else (no)
      :Page.onGet();
    endif
    :Page.onRender();
  endif
else (false)
endif

if (do redirect?) then (yes)
  :redirect process;
else
  if (do forward?) then (yes)
    :Forward request;
  else (no)
    :Render page template;
  endif
endif

stop

@enduml
